### PR TITLE
Replacing the event handler with a temporary script

### PR DESCRIPTION
**Pull request by neroux**
In response to #24. Please review.

### CODE REVIEW

**Comment by neroux** [comment]
What do you exactly mean?

**Comment by tarampampam** [comment]
Injected code is very unstable "by default". Are you sure about your does not break anything? In my case - all works fine without any changes. Can you show pages URIs, where something wrong with current (published) code, please?

**Comment by neroux** [comment]
Please checked the associated issue for further details on where the current implementation breaks, as well as https://github.com/tarampampam/random-user-agent/issues/7#issuecomment-320491642

**Comment by tarampampam** [comment]
Its looks like "JavaScript" protection feature were disabled :)

**Comment by neroux** [comment]
Cant comment on whether the user disabled it but the mentioned site issues a CSP as well.

**Comment by neroux** [comment]
Just to be clear, this would only fix #24 and not #26.

**Comment by neroux** [comment]
A review please @tarampampam. This PR fixes #24 and I've had the extension running with the modification now for the past three weeks and there doesnt seem to be any issues, hence merging it should be fine.

**Comment by neroux** [comment]
Patch works, merged

**Pull request merged**
